import { Satisfy } from "next/font/google";
import "./globals.css";
import StyledComponentRegistry from "@/lib/AntRegistry";
import { Toaster } from "sonner";

const satisfy = Satisfy({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-satisfy",
});

export const metadata = {
  title: "Chat wave",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satisfy.variable}`}>
        <StyledComponentRegistry>
          <Toaster richColors position="top-center" />
          {children}
        </StyledComponentRegistry>
      </body>
    </html>
  );
}
