import { Satisfy } from "next/font/google";
import "./globals.css";
import StyledComponentRegistry from "@/lib/AntRegistry";
import { Toaster } from "sonner";
import { AuthProvider } from "./Providers";

const satisfy = Satisfy({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-satisfy",
});

export const metadata = {
  title: "Chat wave",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satisfy.variable}`}>
        <AuthProvider>
          <StyledComponentRegistry>
            <Toaster richColors position="top-center" />
            {children}
          </StyledComponentRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}
