import { Poppins, Satisfy } from "next/font/google";
import "./globals.css";
import StyledComponentRegistry from "@/lib/AntRegistry";
import AuthProvider from "@/lib/SessionProvider";
import { getServerSession } from "next-auth";

const satisfy = Satisfy({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-satisfy",
});

export const metadata = {
  title: "Chat wave",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satisfy.variable}`}>
        <StyledComponentRegistry>{children}</StyledComponentRegistry>
      </body>
    </html>
  );
}
